// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/news.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NewsService {
  public static partial class NewsFetcher
  {
    static readonly string __ServiceName = "news.NewsFetcher";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::NewsService.ArticleResponse> __Marshaller_news_ArticleResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NewsService.ArticleResponse.Parser));
    static readonly grpc::Marshaller<global::NewsService.ArticleRequest> __Marshaller_news_ArticleRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NewsService.ArticleRequest.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::NewsService.ArticleResponse> __Method_GetAllArticles = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::NewsService.ArticleResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAllArticles",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_news_ArticleResponse);

    static readonly grpc::Method<global::NewsService.ArticleRequest, global::NewsService.ArticleResponse> __Method_GetArticle = new grpc::Method<global::NewsService.ArticleRequest, global::NewsService.ArticleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetArticle",
        __Marshaller_news_ArticleRequest,
        __Marshaller_news_ArticleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NewsService.NewsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for NewsFetcher</summary>
    public partial class NewsFetcherClient : grpc::ClientBase<NewsFetcherClient>
    {
      /// <summary>Creates a new client for NewsFetcher</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NewsFetcherClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NewsFetcher that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NewsFetcherClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NewsFetcherClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NewsFetcherClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::NewsService.ArticleResponse> GetAllArticles(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllArticles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::NewsService.ArticleResponse> GetAllArticles(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAllArticles, null, options, request);
      }
      public virtual global::NewsService.ArticleResponse GetArticle(global::NewsService.ArticleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetArticle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NewsService.ArticleResponse GetArticle(global::NewsService.ArticleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetArticle, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NewsService.ArticleResponse> GetArticleAsync(global::NewsService.ArticleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetArticleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NewsService.ArticleResponse> GetArticleAsync(global::NewsService.ArticleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetArticle, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NewsFetcherClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NewsFetcherClient(configuration);
      }
    }

  }
}
#endregion
